### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by devikamanoj**
I have made some changes. please review. Thankyou

### CODE REVIEW

**Comment by AvidCoder101** [comment]
@devikamanoj could you please explain why you closed this PR? Maybe if I understand, then we could look at reopening and merging if we can :)

**Comment by devikamanoj** [comment]
@AvidCoder101 

> @devikamanoj could you please explain why you closed this PR? Maybe if I understand, then we could look at reopening and merging if we can :)

Actually, I closed it by mistake. It was a slight change in README.md .

**Review by AvidCoder101 — CHANGES_REQUESTED** [review]
@devikamanoj thanks so much for contributing! Could I please request that you keep the images of the code, as this is commonly used and is the format that all of the repositories in the org use to guide people. Thank you

**Comment by AvidCoder101** [comment]
@devikamanoj I have also invited you to the organisation. Once you join, please remember to set you membership to public.

**Comment by devikamanoj** [comment]
> @devikamanoj thanks so much for contributing! Could I please request that you keep the images of the code, as this is commonly used and is the format that all of the repositories in the org use to guide people. Thank you

Yeah Sure

**Comment by AvidCoder101** [comment]
@devikamanoj do you need any help? If so, please feel free to ask for some.

**Comment by AvidCoder101** [comment]
@devikamanoj I am closing this PR due to inactivity. Please feel free to reopen if you'd like to carry on working with it 🙂

**Pull request closed without merging**
